FROM python:3.7-slim-buster
ENV DEBIAN_FRONTEND noninteractive

#get latest python & blender related dependencies
RUN apt-get update && apt-get install -y --no-install-recommends apt-utils python3 python3-virtualenv \
python3-dev python3-pip libgomp1 \
&& rm -rf /var/lib/apt/lists/*

#get the dependencies for the script
RUN mkdir -p /local/

# `dill` needed for discomp
RUN pip install requests pathlib dill

RUN pip install \
catboost==0.20.2 \
disco \
discomp \
lightgbm==2.3.1 \
numpy==1.16.1 \
pandas==0.25.3 \
scikit-learn==0.22 \
scipy==1.4.0 \
tqdm==4.41.0 \
xgboost==0.90

# Entry point for dis.co
WORKDIR /local/
ENTRYPOINT ["python", "-u"]
